version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo 

    steps:
      - checkout

      - run: pip install -r requirements.txt

      - run: python manage.py makemigrations && python manage.py migrate

      - run: python manage.py test tests.unit

      - run: python manage.py test tests.integration

      - run: python manage.py test tests.system

workflows:
  version: 2
  build:
    jobs:
        - build

workflows:
  version: 2
  build:
    jobs:
        - build

      triggers:
        - schedule:
            cron: "55 12 * * 1"  # Запуск в 12:55 каждого понедельника
            filters:
              branches:
                only:
                  - main  # Запуск только на ветке master
        - push:
            branches:
              only:
                - main
