version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run: pip install -r requirements.txt

      - run: python manage.py makemigrations && python manage.py migrate

      - run: python manage.py test tests.unit

      - run: python manage.py test tests.integration

      - run: python manage.py test tests.system

workflows:
  version: 2
  build:
    jobs:
      - tests
      
workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "50 9 * * 1"  # Запуск в 12:55 каждого понедельника
          filters:
            branches:
              only:
                - main
